FROM fractalizer/debian_custom

RUN mkdir -p /usr/share/man/man1 && \
    apt-get install -y --no-install-recommends \
    openjdk-8-jre openjdk-8-jdk perl make

RUN git clone https://github.com/rjust/defects4j && \ 
    cd defects4j && \
    cpan App:cpanminus && cpanm --installdeps . && \ 
    cpanm DBI && \
    ./init.sh

ENV PATH="/defects4j/framework/bin:${PATH}"
