FROM fractalizer/debian_custom

RUN apt-get install --no-install-recommends -y  \
      python-pip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

## FlawFinder
RUN pip install flawfinder
