FROM debian

RUN apt-get update && \
    apt-get install -y \
      ca-certificates \
      git gcc make autoconf build-essential libpcre3-dev
 

RUN  git clone https://github.com/CoolerVoid/Mosca && \
      cd Mosca && \
      make
RUN ln -s /Mosca/mosca /usr/bin/mosca
